<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Значение N</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
<form method="post">
        <label for="value_n">Длина слова:</label>
        <input type="text" name="lenght" id="value_n" placeholder="Значение N">
    <button type="submit" name="submit">submit</button>
</form>
</body>
</html>